nama : SAHRUL-GUNAWAN-WIN10

aktif: alur kerja_pengiriman

Pekerjaan:
  membangun:

    berjalan pada: windows-terbaru

    tangga:
    - nama: UNDUH AKSES NGROK
      jalankan: |
        Memanggil-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stabil-windows-amd64.zip -OutFile ngrok.zip
        Panggil-WebRequest https://raw.githubusercontent.com/SahrulGunawan-ID/FREE-RDP/refs/heads/main/MODULE/START.bat -OutFile start.bat
        Panggil-WebRequest https://raw.githubusercontent.com/SahrulGunawan-ID/FREE-RDP/refs/heads/main/MODULE/WALLPAPER.bat -OutFile wallpaper.bat
        Panggil-WebRequest https://raw.githubusercontent.com/SahrulGunawan-ID/FREE-RDP/refs/heads/main/MODULE/LOOP.bat -OutFile loop.bat
    - nama : MENGEXTRAK FILE NGROK
      jalankan: Perluas-Arsipkan ngrok.zip
    - Nama : MENGHUBUNGKAN AKUN NGROK
      jalankan: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      lingkungan:
        NGROK_AUTH_TOKEN: ${{ rahasia.NGROK_AUTH_TOKEN }}
    - Nama : SEDANG MEBERI AKSES TUNGGU
      jalankan: |
        Set-ItemProperty -Jalur 'HKLM:\Sistem\CurrentControlSet\Kontrol\Terminal Server' -nama "fDenyTSConnections" -Nilai 0
        Aktifkan-NetFirewallRule -DisplayGroup "Desktop Jarak Jauh"
        Set-ItemProperty -Jalur 'HKLM:\Sistem\CurrentControlSet\Kontrol\Terminal Server\WinStations\RDP-Tcp' -nama "UserAuthentication" -Nilai 1
        
        salin wallpaper.bat D:\a\wallpaper.bat
    - nama: Buat Terowongan.
      jalankan: Mulai-Proses Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - Nama : PERMINTAAN CPU DAN RAM
      jalankan: cmd /c start.bat
    - Nama : SUKSES TERHUBUNG KE SERVER RDP
      jalankan: cmd /c loop.bat
      
